name: Auto update changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changelog:
    if: github.event.deleted == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update changelog
        env:
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.sha }}
        run: |
          python3 .github/scripts/update_changelog.py

      - name: Commit changelog update
        run: |
          if git diff --quiet --exit-code CHANGELOG.md; then
            echo "No changelog updates to commit."
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add CHANGELOG.md
            git commit -m "chore: update changelog for core script changes"
            git push
          fi
